### ISSUE TITLE
FEniCS-X installation error [Iris-Broadwell]

### ISSUE THREAD

**Issue by ezhilmathik** [jhale/fenicsx-iris-cluster#5]
Hi, 

Thanks for the installation script! However, I am getting some errors after the installation. For example, I am not able to run the [Poisson demo appplication](https://raw.githubusercontent.com/FEniCS/dolfinx/main/python/demo/poisson/demo_poisson.py). I have not changed much in your installation script, except in env-build-fenics.sh, I have included the 
`
module use /opt/apps/resif/iris/2020b/broadwell/modules/all
`
and `TAG=iris-master-r23`

And I am getting the following error:

`
(python-venv) 1 [user-name@iris-072 poisson](2532797 1N/T/28CN)(master %) $ python demo_poisson.py 
Traceback (most recent call last):
  File "demo_poisson.py", line 102, in <module>
    V = FunctionSpace(mesh, ("Lagrange", 1))
  File "/home/users/user-name/fenicsx-iris-master-r23/python-venv/lib/python3.8/site-packages/dolfinx/fem/function.py", line 415, in __init__
    (self._ufc_element, self._ufc_dofmap), module, code = jit.ffcx_jit(
  File "/home/users/user-name/fenicsx-iris-master-r23/python-venv/lib/python3.8/site-packages/dolfinx/jit.py", line 54, in mpi_jit
    return local_jit(*args, **kwargs)
  File "/home/users/user-name/fenicsx-iris-master-r23/python-venv/lib/python3.8/site-packages/dolfinx/jit.py", line 200, in ffcx_jit
    p_jit = get_parameters(jit_parameters)
  File "/home/users/user-name/fenicsx-iris-master-r23/python-venv/lib/python3.8/site-packages/dolfinx/jit.py", line 138, in get_parameters
    user_parameters, pwd_parameters = _load_parameters()
  File "/home/users/user-name/fenicsx-iris-master-r23/python-venv/lib/python3.8/site-packages/dolfinx/jit.py", line 102, in _load_parameters
    user_parameters = json.load(f)
  File "/opt/apps/resif/iris/2020b/broadwell/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/opt/apps/resif/iris/2020b/broadwell/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/apps/resif/iris/2020b/broadwell/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/apps/resif/iris/2020b/broadwell/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)
`

Could you please give me some tips on how to fix this error?

Thanks!

**Comment by jhale** [comment]
Delete the following directory: `rm -r ~/.config/dolfinx`. I made a mistake with the syntax of this file in a previous version of these build scripts.

If you are at the University I would very much like to know who you are so please do feel free to drop my a line at jack.hale@uni.lu !

**Comment by jhale** [comment]
Could you make a pull request with the changes you made to get it working on iris?

`module use /opt/apps/resif/iris/2020b/broadwell/modules/all`

**Comment by ezhilmathik** [comment]
Thanks! I have created the pull request.
